// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASEYuBF15sZ-fePbeSZ4YEU3AJX3adaUg',
    appId: '1:975669088486:web:dcbee79c1e90e4df9f6b27',
    messagingSenderId: '975669088486',
    projectId: 'socialmedia-43625',
    authDomain: 'socialmedia-43625.firebaseapp.com',
    storageBucket: 'socialmedia-43625.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJmT_XF4INUqCuSywkk2JM5Kmx-L5ijCw',
    appId: '1:975669088486:android:3c3cda62e75d618e9f6b27',
    messagingSenderId: '975669088486',
    projectId: 'socialmedia-43625',
    storageBucket: 'socialmedia-43625.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaQNlkhxKlEOCyBjyCf8hdbGsS4KjnlXs',
    appId: '1:975669088486:ios:fd39db1fbd2e58729f6b27',
    messagingSenderId: '975669088486',
    projectId: 'socialmedia-43625',
    storageBucket: 'socialmedia-43625.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaQNlkhxKlEOCyBjyCf8hdbGsS4KjnlXs',
    appId: '1:975669088486:ios:fd39db1fbd2e58729f6b27',
    messagingSenderId: '975669088486',
    projectId: 'socialmedia-43625',
    storageBucket: 'socialmedia-43625.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASEYuBF15sZ-fePbeSZ4YEU3AJX3adaUg',
    appId: '1:975669088486:web:b4e0d14c129150129f6b27',
    messagingSenderId: '975669088486',
    projectId: 'socialmedia-43625',
    authDomain: 'socialmedia-43625.firebaseapp.com',
    storageBucket: 'socialmedia-43625.firebasestorage.app',
  );
}
